Update weaver-kube code with the latest changes to the weaver@ module.
Note that since we're not releasing this code, so nothing is tagged yet.

diff --git a/dev/build_and_test b/dev/build_and_test
--- a/dev/build_and_test
+++ b/dev/build_and_test
@@ -53,16 +53,16 @@ function cmd_vet() {
 }
 
 function cmd_lint() {
-  if ! exists golangci-lint; then
-    printf "golangci-lint not found; install via\ngo install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2\n" >&2
+  if ! exists staticcheck; then
+    printf "staticcheck not found; install via\ngo install honnef.co/go/tools/cmd/staticcheck@v0.4.3\n" >&2
     exit 1
   fi
 
-  golangci-lint --timeout=10m run ./...
+  staticcheck ./...
 
   # Run unused check while skipping uses found in tests. This helps us
   # identify non-test code that is only used from tests.
-  golangci-lint --timeout=10m run --enable unused --tests=false ./...
+  staticcheck -tests=false ./...
 }
 
 function cmd_test() {
@@ -76,7 +76,7 @@ function cmd_testrace() {
 function main() {
   cmds="$@"
   if [[ $# == 0 ]]; then
-    cmds="tidy generate build vet test testrace"
+    cmds="tidy generate build vet lint test testrace"
   fi
 
   for cmd in $cmds; do
